name: Build and Deploy

On:
Push:
Branches:
- master
jobs:
build-and-deploy:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: action/checkout@v1
- uses: action/setup-node@v1
with:
node-version:'10.x'
- uses: actions/cache@v1
with:
path: ~/.npm
key: ${{ runner.os }}-node-${{ hasFiles('**/package-lock.json')}}
restore-keys: |
${{runner.os}}-node-
-name: Build
run: |
npm install
npm run-script deploy
-name: Deploy
uses: CarlosFTG/github-pages-deploy-action@releases/v3
with:
GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
BRANCH: gh-pages
FOLDER:dist/taxi-mail-sender